import { describe, expect, it } from "vitest"; import { parseArxivFeed, parseGitHubTrending, parseHackerNews, parseInfoQFeed, parseRedditListing, parseYouTubeFeed } from "../scripts/scrape";
describe("scrapers",()=>{
  it("parses Hacker News rows",()=>{const html='<table><tr class="athing" id="9"><td class="title"><span class="titleline"><a href="https://x.dev">AI agents arrive</a></span></td></tr><tr><td><span class="score">123 points</span></td></tr></table>';expect(parseHackerNews(html)[0]).toMatchObject({id:"hn-9",score:123,topic:"AI & Agents"})});
  it("parses GitHub Trending cards",()=>{const html='<article class="Box-row"><h2><a href="/acme/tool">acme/tool</a></h2><p>Fast TypeScript SDK</p><span itemprop="programmingLanguage">TypeScript</span><a href="/acme/tool/stargazers">1,234</a></article>';expect(parseGitHubTrending(html)[0]).toMatchObject({score:1234,language:"TypeScript",topic:"Developer Tools"})});
  it("parses Reddit OAuth listings",()=>{const listing={data:{children:[{data:{id:"abc",title:"New JavaScript framework",permalink:"/r/webdev/abc",score:40,num_comments:5,subreddit:"webdev"}}]}};expect(parseRedditListing(listing)[0]).toMatchObject({id:"reddit-abc",source:"Reddit",score:45,metric:"engagement"})});
  it("parses arXiv research metadata",()=>{const xml='<feed><entry><id>https://arxiv.org/abs/2609.001</id><title>Reliable AI Agents</title><summary>A study of agent reliability.</summary><category term="cs.AI"/></entry></feed>';expect(parseArxivFeed(xml)[0]).toMatchObject({source:"arXiv",metric:"rank",topic:"AI & Agents"})});
  it("parses InfoQ article feeds",()=>{const xml='<rss><channel><item><guid>42</guid><title>Fast APIs in production</title><link>https://infoq.com/a</link><description><![CDATA[<p>An engineering report.</p>]]></description></item></channel></rss>';expect(parseInfoQFeed(xml)[0]).toMatchObject({source:"InfoQ",score:15,url:"https://infoq.com/a"})});
  it("parses keyless YouTube channel feeds",()=>{const xml='<feed xmlns:yt="http://www.youtube.com/xml/schemas/2015" xmlns:media="http://search.yahoo.com/mrss/"><entry><yt:videoId>abc123</yt:videoId><title>Build a TypeScript API</title><published>2026-09-03T12:00:00Z</published><author><name>Example Dev</name></author><media:group><media:description>A practical tutorial</media:description><media:thumbnail url="https://i.ytimg.com/vi/abc123/mqdefault.jpg"/></media:group></entry></feed>';expect(parseYouTubeFeed(xml)[0]).toMatchObject({id:"youtube-abc123",source:"YouTube",kind:"video",metric:"rank",imageUrl:"https://i.ytimg.com/vi/abc123/mqdefault.jpg"})});
});
